// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipbrqtxxfkamqmtrddis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwYnJxdHh4ZmthbXFtdHJkZGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTAwODgsImV4cCI6MjA3MTg2NjA4OH0.j_XJzn7MaedFBY2lCg7J62doI8fKJDSCeeMiuMemB3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});